spring:
 h2:
  console:
   enabled: true
   path: /h2-console
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: create-drop
# datasource:
#  url: jdbc:mysql://192.168.0.27:3307
#  username: root
#  password: 1234


upbit:
 url: "https://api.upbit.com/v1/market/all"
