spring:
 h2:
  console:
   enabled: true
   path: /h2-console

 jpa:
  show-sql: true
  properties:
   hibernate:
    format_sql: true
  hibernate:
   ddl-auto: create-drop

 jackson:
  serialization:
   fail-on-empty-beans: false
# datasource:
#  url: jdbc:mysql://192.168.0.27:3307
#  username: root
#  password: 1234

logging:
 level:
  org:
   hibernate:
    type:
     descriptor:
      sql: trace

upbit:
 url: "https://api.upbit.com/v1/market/all"

jwt:
 secret: "a1234b5678c9a1234b5678c9a1234b5678c9"
